### ISSUE TITLE
Storage Lab

### ISSUE THREAD

**Issue by rakrawat** [rakrawat/SEBC#4]

**Comment by rakrawat** [comment]
The replication peer was added and a job was scheduled. The exercise encountered issue in the last step when copying file from a remote server.

**Comment by mfernest** [comment]
Notes:
- The replication failed at an expected point -- no worries
- It would have been interested to see the output of the your `hdfs cacheadmin` commands -- they make good reference notes
- You'll want to know the page that shows the state of your NameNodes in HA, not just the list of instances
- CM user page -- good

Complete
